default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tu_usuario
  password: nueva_contraseña
  host: localhost

development:
  <<: *default
  database: 2024_2_grupo_23_development

test:
  <<: *default
  database: 2024_2_grupo_23_test

production:
  <<: *default
  #database: 2024_2_grupo_23_production
  #username: 2024_2_grupo_23
  #password: <%= ENV['2024_2_GRUPO_23_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>